class ErrorEnum:
    class Service:
        INVALID_REFERRED_TELEGRAM_ID = "SERVICE_INVALID_REFERRED_TELEGRAM_ID"
        INVALID_REFERRER_AND_REFERRED = "SERVICE_INVALID_REFERRER_AND_REFERRED"
        USER_ALREADY_HAS_A_REFERRER = "SERVICE_UESR_ALREADY_HAS_A_REFERER"

