# Generated by Django 4.1.3 on 2026-01-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = []
